# US States and Territories ISO2 code mappings
# Includes common variations, misspellings, and translations

STATE_TERRITORY_MAPPINGS = {
    # US States
    'alabama': 'AL',
    'alaska': 'AK',
    'arizona': 'AZ',
    'arkansas': 'AR',
    'california': 'CA',
    'colorado': 'CO',
    'connecticut': 'CT',
    'delaware': 'DE',
    'florida': 'FL',
    'georgia': 'GA',
    'hawaii': 'HI',
    'idaho': 'ID',
    'illinois': 'IL',
    'indiana': 'IN',
    'iowa': 'IA',
    'kansas': 'KS',
    'kentucky': 'KY',
    'louisiana': 'LA',
    'maine': 'ME',
    'maryland': 'MD',
    'massachusetts': 'MA',
    'michigan': 'MI',
    'minnesota': 'MN',
    'mississippi': 'MS',
    'missouri': 'MO',
    'montana': 'MT',
    'nebraska': 'NE',
    'nevada': 'NV',
    'new hampshire': 'NH',
    'new jersey': 'NJ',
    'new mexico': 'NM',
    'new york': 'NY',
    'north carolina': 'NC',
    'north dakota': 'ND',
    'ohio': 'OH',
    'oklahoma': 'OK',
    'oregon': 'OR',
    'pennsylvania': 'PA',
    'rhode island': 'RI',
    'south carolina': 'SC',
    'south dakota': 'SD',
    'tennessee': 'TN',
    'texas': 'TX',
    'utah': 'UT',
    'vermont': 'VT',
    'virginia': 'VA',
    'washington': 'WA',
    'west virginia': 'WV',
    'wisconsin': 'WI',
    'wyoming': 'WY',
    
    # US Territories
    'american samoa': 'AS',
    'guam': 'GU',
    'northern mariana islands': 'MP',
    'puerto rico': 'PR',
    'united states minor outlying islands': 'UM',
    'u.s. minor outlying islands': 'UM',
    'us minor outlying islands': 'UM',
    'virgin islands': 'VI',
    'u.s. virgin islands': 'VI',
    'us virgin islands': 'VI',
    
    # Spanish translations
    'nueva york': 'NY',
    'california': 'CA',
    'florida': 'FL',
    'texas': 'TX',
    
    # Chinese translations (Traditional and Simplified)
    '紐約': 'NY',
    '纽约': 'NY',
    '加州': 'CA',
    '加利福尼亚': 'CA',
    '佛羅里達': 'FL',
    '佛罗里达': 'FL',
    '德克薩斯': 'TX',
    '德克萨斯': 'TX',
}

# Common misspellings and variations
STATE_TERRITORY_VARIATIONS = {
    'new yrk': 'NY',
    'newyork': 'NY',
    'n.y.': 'NY',
    'ny': 'NY',
    'nyk': 'NY',
    'californya': 'CA',
    'calif': 'CA',
    'ca': 'CA',
    'flordia': 'FL',
    'fl': 'FL',
    'pensylvania': 'PA',
    'pa': 'PA',
    'texas': 'TX',
    'tx': 'TX',
    'united state minor outlying islands': 'UM',
    'us minor outlying island': 'UM',
}
